name: fleishco
channels:
        - conda-forge
        - pytorch
        - defaults
dependencies:
        - python=3.7
        - matplotlib
        - numpy
        - pandas
        - scipy
        - flake8
        - psycopg2
        - jupyter
        - jupyterlab
        - ipython
        - pip
        - scikit-learn
        - imageio=2.5.0
        - tqdm=4.36.1
        - networkx
        - pytables
        - requests
        - awscli
        - s3fs
        - pytorch
        - torchtext
        - torchvision
        - cudatoolkit=10.1
        - tensorboard
        - sqlalchemy
        - xlwings
        - pip:
                - pprofile
                - jsons
                - tensorflow
                - yfinance
                - lxml
                - beautifulsoup4
                - calcbench-api-client
                - backoff
                - absl-py
                - grpcio
                - QuantLib
                - sentencepiece
